# =========================
# EXPERIMENT SETTING
# =========================
exp:
  feature_mode: 'baseline'  # choices: [baseline, exp1, exp2, exp3, exp4, exp5, exp6]
  device: 'cuda:0'
  seed: 42

# =========================
# DATA PATHS & PARAMS
# =========================
data:
  base_dir: 'highD'
  batch_size: 512
  num_workers: 32
  history_frames: 15
  future_frames: 25

# =========================
# MODEL PARAMS (GRIP++)
# =========================
model:
  max_hop: 2
  num_node: 9  # Ego + 8 Neighbors (MAX_NEIGHBORS + 1)
  edge_importance_weighting: true

# =========================
# TRAINING PARAMS
# =========================
train:
  epochs: 300
  lr: 0.001
  weight_decay: 0.0001
  ckpt_dir: 'ckpts'